annonces_site:
    resource: "@AnnoncesSiteBundle/Controller/"
    type:     annotation
    prefix:   /

annonces_utilisateurs:
    resource: "@AnnoncesUtilisateursBundle/Controller/"
    type:     annotation
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"