<?php

namespace Annonces\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AnnoncesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{

   public function getAnnonces()
    {
        $query = $this->_em->createQuery('SELECT a FROM AnnoncesSiteBundle:Annonce a');
        return $query;
    }

    public function getCount()
    {
        $query = $this->_em->createQuery('SELECT COUNT(a.id) FROM AnnoncesSiteBundle:Annonce a');
        $count = $query->getSingleScalarResult();

        return $count;
    }


}
